config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  devise_for :users

  resources :items do
    patch "move", on: :member
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id            :integer          not null, primary key
#  category      :string
#  item          :string
#  picture       :string
#  related_items :string
#  status        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#
class Item < ApplicationRecord
  belongs_to :user

  validates :item, presence: true

  enum status: {
    cart: "cart",
    end_soon: "end_soon",
    in_stock: "in_stock"
}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy move ]

  def move
    if @item.cart?
      @item.end_soon!
    elsif @item.end_soon?
      @item.in_stock!
    else
      @item.end_soon!
    end

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item updated" }

      format.js
    end
  end

  # GET /items or /items.json
  def index
    items = Item.where(category: "fruits")
    items.update_all(category: "<i class=\"fa-solid fa-apple-whole\"></i>")
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /items or /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:item, :related_items, :status, :category, :picture)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<li id="<%= dom_id item, :form %>" class="list-group-item">
  <%= form_with(model: item, local: false) do |form| %>
    <div class="mb-2">
      <%= form.label :item, class: "visually-hidden" %>
      <%= form.text_field :item, class: "form-control" %>
    </div>

      <div>
      <div class="d-grid">
        <%= form.submit class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>

</li>

app/views/items/_item.html.erb
<li id="<%= dom_id(item) %>" class="list-group-item">
  <div>
    <%= item.item %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to move_item_path(item), class: "btn btn-link", method: :patch, remote: true do %>
          <% if item.cart? %>
            <i class="fa-sharp fa-solid fa-play"></i>
          <% elsif item.end_soon? %>
            <i class="fa-regular fa-circle-check"></i>
          <% else %>
            <i class="fa-sharp fa-solid fa-backward"></i>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to edit_item_path(item), remote: true, class: "btn btn-link" do %>
          <i class="fa-sharp fa-solid fa-pen-to-square"></i>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="d-grid gap-2">
        <%= link_to item, method: :delete, remote: true, class: "btn btn-link" do %>
          <i class="fa-sharp fa-solid fa-trash-can"></i>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/items/create.js.erb
var new_item = $("<%= j(render @item) %>");

new_item.hide();

$("#form_item").after(new_item);

new_item.slideDown();

$("#form_item #item_body").val("");

app/views/items/destroy.js.erb
$("#<%= dom_id @item %>").slideUp(function() {
  this.remove();
});

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>
<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/edit.js.erb
$("#<%= dom_id @item %>").replaceWith("<%= j(render "items/form", item: @item)%>");

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Cart
      </div>

      <ul id="cart_list" class="list-group list-group-flush">
        <%= render "items/form", item: current_user.items.build %>
        <%= render current_user.items.cart.order(created_at: :desc) %>
      </ul>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        End Soon
      </div>

      <ul id="end_soon_list" class="list-group list-group-flush">
        <%= render current_user.items.end_soon.order(updated_at: :desc) %>
      </ul>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        In Stock!
      </div>

      <ul id="in_stock_list" class="list-group list-group-flush">
        <%= render current_user.items.in_stock.order(updated_at: :desc) %>
      </ul>
    </div>
  </div>
</div>

app/views/items/move.js.erb
$("#<%= dom_id @item %>").remove();

var updated_item = $("<%= j(render @item) %>");

$("#<%= @item.status %>_list").prepend(updated_item);

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item.item %>
</p>

<p>
  <strong>Related items:</strong>
  <%= @item.related_items %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @item.picture %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/update.js.erb
$("#<%= dom_id @item, :form %>").replaceWith("<%= j(render @item)%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Grocery Items List</title>
    <%= csrf_meta_tags %>

    <!-- Expand the number of characters we can use in the document beyond basic ASCII 🎉 -->
    <meta charset="utf-8">

    <!-- Make it responsive to small screens -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csp_meta_tag %>

    <%= render "shared/cdn_assets" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="mb-5">
    <%= render "shared/navbar" %>

    <div class="container">
      <%= render "shared/flash_messages" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_cdn_assets.html.erb
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light mb-3">
  <div class="container">
    <a class="navbar-brand" href="/">Items</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>